<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--suppress MsbuildTargetFrameworkTagInspection -->
        <TargetFrameworks>netstandard2.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild> <!-- Generates a package at build -->
        <IncludeBuildOutput>false</IncludeBuildOutput> 
        <IsDeveloperDependency>true</IsDeveloperDependency>
        <DevelopmentDependency>true</DevelopmentDependency>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IncludeBuildOutput>false</IncludeBuildOutput> 

        <!-- Package metadata -->
        <PackageId>CodeOfChaos.BlazorIcons.Lucide.SourceGenerators</PackageId>
        <Version>1.14.0</Version>
        <Description>Use Lucide in your Blazor apps</Description>
        <Authors>CodeOfChaos, Lucide</Authors>
    </PropertyGroup>

    <!-- Package dependencies -->
    <ItemGroup>
        <PackageReference Include="IsExternalInit">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="CodeOfChaos.GeneratorTools" Pack="true" GeneratePathProperty="true" PrivateAssets="all" />
        <PackageReference Include="System.Text.Json" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="lib/netstandard2.0" Visible="false" />
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>


</Project>
