<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Unions" />
        <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
        <PackageReference Include="CodeOfChaos.Extensions.Serilog" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Library" />
        <PackageReference Include="CodeOfChaos.CliArgsParser.Generators">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Bcl.Memory" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Playwright" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Lucide.SourceGenerators\InfiniLore.Lucide.SourceGenerators.csproj" />
    </ItemGroup>

</Project>
