<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.83.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="TUnit" Version="0.75.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\InfiniLore.Lucide\InfiniLore.Lucide.csproj" />
    </ItemGroup>

</Project>
