<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeOfChaos.Extensions" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="TUnit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\CodeOfChaos.BlazorIcons.Lucide\CodeOfChaos.BlazorIcons.Lucide.csproj" />
    </ItemGroup>

</Project>
