<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>

        
        <PackageId>CodeOfChaos.BlazorIcons.Lucide</PackageId>
        <Version>1.28.0</Version>
        <Description>Use Lucide in your Blazor apps</Description>
        <Authors>CodeOfChaos, Lucide</Authors>
        
        
        <LucideIconNodes Condition=" '$(NODE_PATH)' != '' ">$(NODE_PATH)/lucide-static/icon-nodes.json</LucideIconNodes>
        <LucideIconNodes Condition=" '$(NODE_PATH)' == '' ">$(MSBuildProjectDirectory)/node_modules/lucide-static/icon-nodes.json</LucideIconNodes>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CodeOfChaos.BlazorIcons.Lucide.SourceGenerators\CodeOfChaos.BlazorIcons.Lucide.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup Label="Lucide Files">
        

        <AdditionalFiles Include="$(LucideIconNodes)" Link="%(FileName)%(Extension)" Pack="false" />
    </ItemGroup>

    <ItemGroup Label="Packing">
        
        <None Include="node_modules/lucide-static/icons/**/*.svg" Pack="false" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Properties\launchSettings.json" />
    </ItemGroup>

</Project>