name: Publish Packages

on:
  push:
    tags:
      - 'v*.*.*' # Match version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js for lucide-static
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      # Step 3: Install npm dependencies
      - name: Install npm dependencies
        run: npm install
        
      - name: Debug node_modules location
        run: ls -lh ${{ github.workspace }}/node_modules/lucide-static/icons || echo "Icons directory not found!"

      # Step 4: Setup .NET for building .NET projects
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Step 5: Restore .NET project dependencies
      - name: Build .NET projects (with NODE_PATH)
        run: |
          export NODE_PATH=${{ github.workspace }}/node_modules
          dotnet build InfiniLore.Lucide.sln --configuration Release --no-restore

      # Step 6: Build the .NET projects
      - name: Build .NET projects
        run: dotnet build InfiniLore.Lucide.sln --configuration Release --no-restore

      # Step 7: Link node_modules to tests (ensures node_modules is available for test runtime)
      - name: Ensure node_modules path for tests
        run: echo "NODE_PATH=${{ github.workspace }}/node_modules" >> $GITHUB_ENV

      # Step 8: Run tests
      ## NOTE: Ensure tests can access node_modules safely and verify SVG path exists
      - name: Run tests - Tests.InfiniLore.Lucide
        run: |
          ls -lh node_modules/lucide-static/icons || echo "Icons directory not found!"
          dotnet run -c Release --no-restore --no-build --framework net9.0
        working-directory: "tests/Tests.InfiniLore.Lucide"

      # Step 9: Publish to NuGet
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push src/InfiniLore.Lucide/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push src/InfiniLore.Lucide.Data/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push src/InfiniLore.Lucide.Generators.Raw/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate