name: "Shared: .NET Testing"

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup Node.js
                uses: actions/setup-node@v7
                with:
                    node-version: 24

            -   name: Install Dependencies
                run: npm install
                working-directory: ${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide

            -   name: Setup .NET
                uses: actions/setup-dotnet@v5
                with:
                    dotnet-version: |
                        8.x
                        9.x
                        10.x

            -   name: Setup Python
                uses: actions/setup-python@v7
                with:
                    python-version: 3.14

            -   name: Export node_modules path
                run: |
                    echo "NODE_PATH=${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide/node_modules" >> $GITHUB_ENV
                    export NODE_PATH=${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide/node_modules

            -   name: Export Actions Runtime
                uses: actions/github-script@v9
                with:
                    script: |
                        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN']);
                        core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL']);

            -   name: Restore NuGet packages
                run: dotnet restore CodeOfChaos.BlazorIcons.GitHubActions.Testing.slnf

            -   name: Build projects
                run: dotnet build CodeOfChaos.BlazorIcons.GitHubActions.Testing.slnf --configuration Release --no-restore

            -   name: Run tests
                run: dotnet test --solution CodeOfChaos.BlazorIcons.GitHubActions.Testing.slnf --configuration Release --no-restore --no-build
