name: "Shared: .NET Testing"

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5

            -   name: Setup Node.js
                uses: actions/setup-node@v6
                with:
                    node-version: 24

            -   name: Install Dependencies
                run: npm install
                working-directory: ${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide

            -   name: Setup .NET
                uses: actions/setup-dotnet@v5
                with:
                    dotnet-version: |
                        8.x
                        9.x
                        10.x

            -   name: Export node_modules path
                run: |
                    echo "NODE_PATH=${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide/node_modules" >> $GITHUB_ENV
                    export NODE_PATH=${{ github.workspace }}/src/CodeOfChaos.BlazorIcons.Lucide/node_modules

            -   name: Restore NuGet packages
                run: dotnet restore CodeOfChaos.BlazorIcons.GitHubActions.Testing.slnf

            -   name: Build projects
                run: dotnet build --configuration Release --no-restore

            -   name: Run tests
                run: dotnet test --solution CodeOfChaos.BlazorIcons.GitHubActions.Testing.slnf --configuration Release --no-restore --no-build
